sudo: required

services:
  - docker

matrix:
  include:
    - env:
      - SUBFOLDER=cwmonitor
      - REPO=cucloudcollab/cwmonitor
      - TAG=$TRAVIS_BUILD_NUMBER
      services:
        - docker

    - env:
      - SUBFOLDER=testrepo
      - REPO=cucloudcollab/testrepo
      - TAG=$TRAVIS_BUILD_NUMBER
      services:
        - docker

script:
  - docker build $SUBFOLDER -t $REPO:$TAG

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $REPO:$TAG
