sudo: required

services:
  - docker

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y nodejs npm
    - sudo npm install -g npm
    - sudo npm install -g dockerlint

matrix:
  include:
    - env:
      - SUBFOLDER=cwmonitor
      - REPO=cucloudcollab/cwmonitor
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

    - env:
      - SUBFOLDER=node_oracle
      - REPO=cucloudcollab/node-oracle
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

    - env:
      - SUBFOLDER=ruby_oracle
      - REPO=cucloudcollab/ruby-oracle
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

    - env:
      - SUBFOLDER=node_puppeteer
      - REPO=cucloudcollab/node-puppeteer
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

    - env:
      - SUBFOLDER=oracle_instantclient
      - REPO=cucloudcollab/oracle-instantclient
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

    - env:
      - SUBFOLDER=pypicloud
      - REPO=cucloudcollab/pypi
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

    - env:
      - SUBFOLDER=xvfb-firefox
      - REPO=cucloudcollab/xvfb-firefox
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

    - env:
      - SUBFOLDER=samlapi
      - REPO=cucloudcollab/samlapi
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

script:
  - dockerlint $SUBFOLDER/Dockerfile
  - docker build $SUBFOLDER -t $REPO:$TAG -t $REPO:latest

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $REPO:$TAG
  - docker push $REPO:latest
