sudo: required

services:
  - docker

matrix:
  include:
    - env:
      - SUBFOLDER=cwmonitor
      - REPO=cucloudcollab/cwmonitor
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

    - env:
      - SUBFOLDER=node_oracle
      - REPO=cucloudcollab/node-oracle
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

    - env:
      - SUBFOLDER=oracle_instantclient
      - REPO=cucloudcollab/oracle-instantclient
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

    - env:
      - SUBFOLDER=pypicloud
      - REPO=cucloudcollab/pypi
      - TAG=$TRAVIS_COMMIT
      services:
        - docker

script:
  - docker run --rm -i lukasmartinelli/hadolint < $SUBFOLDER/Dockerfile
  - docker build $SUBFOLDER -t $REPO:$TAG -t $REPO:latest

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $REPO:$TAG
  - docker push $REPO:latest
